sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: UXi3eYR2xcE4wBO8xYBpYTDv+1bvDAKFlZ/UvXBXf/VJYLnoRn2//OjAX50b58ule6gH01Sq0Jtvl1gJRDou3vhvvc157RqfF5bLDpoKhOLj0EJSDyZojjHUKRs7Ky3pwRa/YUZ5WpN9newohusV3PJdgYqdL33W//gNQRJQXMLX4q+LYuglT13/+5NW5YBdm1Mv6hFRNc/HxwL6dCFI99qQuOJ9WHnxkVCg7Hr+Do9uQBft0OZrabOaZDOLUyRvRfZisutgq8hcBCWstaFWwaIdC0qTNVRLQisv/SqgLkTuCdBM8UCDxAIGxaz8HVPPNaC60oqvEfdZM5HP2l1LwKWYzQJg3UdZ9CKU+FhI++PmfTxBmS6og3siv3OKwsRkxtYooB3FfVaGPMrn2wDOEV32nOvT9T55CkEOtrapATZcyj5VxP7wplX0gawSh1ANt2fEwc2IgpokG/2QcIg+nRHQpw7iQvWjxee1rbXn5ydGPHNxmCbkKHOwZVlYeVwTUu1Sivx1lVPWhxdNMrGjw7tVpuc6quNE2I9qMYTqPMjlLJOqoyCueSi/M72i110D6jihaaYsDR0qEXisRQ9fLgPmuCh62A+ABI8HLpwSW08lW1mGawpb+CdE49cXB3LOpWBnDkvqWQFzxan3Tllf9K58TstF5p8JQflzkHGdqMg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Complete-Works-of-Artemus-Ward-Part-4-To-California-and-Return_3274
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy